### ISSUE TITLE
error with line 16 (import urllib.request)

### ISSUE THREAD

**Issue by joebywan** [stewartmcgown/uds#30]
Have installed the requirements prior to running uds.py, when I do, I'm met with the following error (on ubuntu 18.04).

`File "uds.py", line 16, in <module>
  import urllib.request
ImportError: No mobule named request`

Considering I'm the first to post this, I'm assuming there must be something I've missed installing.  I've gone through and installed python-urllib3 aswell as python3-urllib3 (which reports as up to date, so assuming it's two different names for the same thing).

Any suggestions on what to try next?

**Comment by 78Alpha** [comment]
You can try to setup a Virtual Environment. Pycharm is an IDE that allows this by default, you can install the requirements and "sandbox" test it for information gathering.

**Comment by joebywan** [comment]
Figured it out.  Ubuntu by default uses python2, and this isn't compatible.  

Ran it with python3 after installing all of the requirements and received this error:


![Capture](https://user-images.githubusercontent.com/4845431/57841523-0cbb7d80-780e-11e9-8367-1336b45aff9e.JPG)

**Comment by evansan** [comment]
Fixed. Run `python uds.py`, or `python3 uds.py ` for deb based systems.

**Comment by joebywan** [comment]
Gave it a shot, similar error still unfortunately:

![image](https://user-images.githubusercontent.com/4845431/57906731-55327400-78be-11e9-84f3-808c5d4de990.png)

**Comment by stewartmcgown** [comment]
Have you renamed credentials.json to client_secret.json?

**Comment by joebywan** [comment]
Thanks mate, my bad on not renaming the file.  Seems to be working now :)
